### ISSUE TITLE
installation impossible

### ISSUE THREAD

**Issue by inscriptionweb** [pictuga/morss#10]
salut,

voilà facilement 1 mois et demi que je tente d'installer morss (je ne connais absolument pas python, du coup çà n'aide pas...) sans réussite.

Peu importe la méthode que j'utilise, j'arrive toujours à un problème d'"appli inexistante" et/ou d'import.

Dernier exemple en date (ce soir), en suivant une xxème fois le tuto de https://blog.ronsonchan.com/setting-up-morss-full-text-rss-expander-on-debian-wheezy/ (que tu as mis en avant sur twitter).

lorsque j'arrive à cette étape : 
4 -Set up uWSGI 
c. Test to see if it works, run uwsgi --http-socket :8080 --wsgi-file morss.py --callable cgi_wrapper 
d. Access http://<YOUR IP>:8080 and you should get the morss default page. 

Dans le terminal, j'obtiens :

```
*** Starting uWSGI 2.0.11.1 (32bit) on [Tue Sep 22 20:23:14 2015] ***
compiled with version: 4.6.3 on 21 September 2015 21:44:50
os: Linux-3.18.11+ #781 PREEMPT Tue Apr 21 18:02:18 BST 2015
nodename: raspberrypi
machine: armv6l
clock source: unix
detected number of CPU cores: 1
current working directory: /usr/share/nginx/www/morss
detected binary path: /usr/share/nginx/www/morss/morss_venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3416
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8080 fd 3
Python version: 2.7.3 (default, Mar 18 2014, 05:13:23)  [GCC 4.6.3]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1f8d780
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64256 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "morss.py", line 15, in <module>
    from . import feeds
ValueError: Attempted relative import in non-package
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 10738, cores: 1)
```

Dans mon browser : 

```
Internal Server Error
```

Puis (après la requete dans le browser) dans mon terminal : 

```
--- no python application found, check your startup logs for errors ---
[pid: 10738|app: -1|req: -1/3] 192.168.0.254 () {30 vars in 503 bytes} [Tue Sep 22 20:25:15 2015] GET /favicon.ico => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
```

J'ai du mal à comprendre l'erreur sur la ligne 15 déjà, feeds.py est bien dans le même répertoire que morss.py.

what's wrong ?

**Comment by pictuga** [comment]
Salut,

En fait j'ai récemment effectué qq changements pour faciliter la compatibilité avec uwsgi, mais du coup les commandes de l'article en question ne sont plus tout à fait correctes (elles sont maintenant plus simples).

Est-ce que la commande suivante fonctionne?
```uwsgi --http :8080 --plugin python --wsgi-file main.py```

Commande qu'il faut donc lancer depuis le dossier où `main.py` se trouve. Le message par rapport à `feeds.py` est en réalité normal, il ne faut pas appeler `morss.py` directement.

**Comment by inscriptionweb** [comment]
Yes, çà fonctionne déjà mieux :) 
J'ai tellement essayé de choses qu'au final je mixais pas mal de méthodes entre elles.

Maintenant, j'accède bien à mon morss.html.
En revanche, je n'arrive pas à générer des liens valides comme sur morss.it .

1 - Lorsque je génère un fulltext feed, je vois bien le code xml afficher sur mon browser (à l'url monip/pathtomorss/lienoriginaldufeed.xml, mais je ne peux pas utiliser ce lien (dans un lecteur rss, il ne retrouve absolument rien, alors qu'avec morss.it/liendufeed il me retrouve tout). J'ai l'impression que le fulltext feed n'a jamais existé (ou que sa trace a été perdue).

2 - Lorsque j'ai généré une fois un fulltext feed, impossible de le générer une seconde fois. J'ai ouvert le fichier .db et je retrouve bien tous les feeds générés.


Tout ce que je fais sur mon serveur ne me génère que des liens morts, quand je génère les mêmes liens sur morss.it aucun problème.
J'imagine que c'est moi qui manipule mal l'appli non?

**Comment by pictuga** [comment]
1- Le lecteur de flux rss est-il en ligne ? (Une web app, et non pas un logiciel sur ton ordi) Si c'est le cas, il faut qu'on puisse accéder à ton serveur morss depuis Internet (nécessite de configurer le routeur/box FAI)

2- morss.it n' utilise pas la dernière version de morss. La re-génération du flux est plus lente avec la dernière version (hélas), la faute à une librairie utilisée peu optimisée... Mais si le flux n'est pas du tout re-généré, alors c'est probablement un bug.

**Comment by inscriptionweb** [comment]
Niveau configuration du routeur, tout est ok.

Voici quelques infos sur les erreurs générées : 

-------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------

lors de la requête au serveur pour atteindre index.html:

[pid: 19112|app: 0|req: 1/1] 192.168.0.254 () {38 vars in 652 bytes} [Thu Sep 24 14:44:46 2015] GET / => generated 1066 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 60 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./morss/morss.py", line 662, in cgi_wrapper
    log('ERROR <%s>: %s' % (url, e.message), force=True)
  File "./morss/morss.py", line 656, in cgi_wrapper
    return cgi_app(environ, start_response) or []
  File "./morss/morss.py", line 600, in cgi_app
    rss = Fetch(url, options)
  File "./morss/morss.py", line 343, in Fetch
    raise MorssException('Error downloading feed')
morss.morss.MorssException: Error downloading feed
[pid: 19112|app: 0|req: 2/2] 192.168.0.254 () {38 vars in 603 bytes} [Thu Sep 24 14:44:47 2015] GET /favicon.ico => generated 0 bytes in 331 msecs (HTTP/1.1 500) 2 headers in 65 bytes (0 switches on core 0)





-------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------

lors de la génération d'un fulltext feed :


[pid: 19112|app: 0|req: 3/3] 192.168.0.254 () {40 vars in 762 bytes} [Thu Sep 24 14:46:01 2015] GET /feeds.feedburner.com/michelcollon/rss => generated 145049 bytes in 25063 msecs (HTTP/1.1 200) 3 headers in 90 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./morss/morss.py", line 662, in cgi_wrapper
    log('ERROR <%s>: %s' % (url, e.message), force=True)
  File "./morss/morss.py", line 656, in cgi_wrapper
    return cgi_app(environ, start_response) or []
  File "./morss/morss.py", line 600, in cgi_app
    rss = Fetch(url, options)
  File "./morss/morss.py", line 343, in Fetch
    raise MorssException('Error downloading feed')
morss.morss.MorssException: Error downloading feed
[pid: 19112|app: 0|req: 4/4] 192.168.0.254 () {38 vars in 603 bytes} [Thu Sep 24 14:46:26 2015] GET /favicon.ico => generated 0 bytes in 104 msecs (HTTP/1.1 500) 2 headers in 65 bytes (0 switches on core 0)


-------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------

lors du rappel d'un fulltext feed existant :


Traceback (most recent call last):
  File "./morss/morss.py", line 662, in cgi_wrapper
    log('ERROR <%s>: %s' % (url, e.message), force=True)
  File "./morss/morss.py", line 656, in cgi_wrapper
    return cgi_app(environ, start_response) or []
  File "./morss/morss.py", line 600, in cgi_app
    rss = Fetch(url, options)
  File "./morss/morss.py", line 336, in Fetch
    con = custom_handler(('xml', 'html'), delay).open(url, timeout=TIMEOUT * 2)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "./morss/crawler.py", line 304, in http_open
    resp = addinfourl(BytesIO(data), headers, req.get_full_url(), code)
TypeError: 'buffer' does not have the buffer interface
[pid: 19112|app: 0|req: 5/5] 192.168.0.254 () {38 vars in 681 bytes} [Thu Sep 24 14:47:08 2015] GET /feeds.feedburner.com/michelcollon/rss => generated 0 bytes in 67 msecs (HTTP/1.1 500) 2 headers in 65 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./morss/morss.py", line 662, in cgi_wrapper
    log('ERROR <%s>: %s' % (url, e.message), force=True)
  File "./morss/morss.py", line 656, in cgi_wrapper
    return cgi_app(environ, start_response) or []
  File "./morss/morss.py", line 600, in cgi_app
    rss = Fetch(url, options)
  File "./morss/morss.py", line 336, in Fetch
    con = custom_handler(('xml', 'html'), delay).open(url, timeout=TIMEOUT * 2)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "./morss/crawler.py", line 304, in http_open
    resp = addinfourl(BytesIO(data), headers, req.get_full_url(), code)
TypeError: 'buffer' does not have the buffer interface
[pid: 19112|app: 0|req: 6/6] 192.168.0.254 () {38 vars in 681 bytes} [Thu Sep 24 14:47:08 2015] GET /feeds.feedburner.com/michelcollon/rss => generated 0 bytes in 65 msecs (HTTP/1.1 500) 2 headers in 65 bytes (0 switches on core 0)



-------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------

J'ia testé sur un python en version 3.* et une 4.3. Peut-être qu'il faut que je rebascule en 2.7 ?

**Comment by pictuga** [comment]
Les 2 premières erreurs sont normales. Elles disent que le flux et le index.html ont bien été envoyés (Code 200), et que la requête de `favicon.ico` a échoué, ce qui est normal puisque morss cherche alors le flux `http://favicon.ico/` qui n'existe pas.

Le 3e message semble être bel et bien un bug de morss.
Je vais regarder ça.

**Comment by inscriptionweb** [comment]
Hey,

j'ai hésité à ouvrir une nouvelle issue avec un titre correct.
J'ai exactement le même soucis de disponibilité du lien.
Au delà de sa génération par morss, on ne peut rien en faire.
Il ne se met pas à jour  et il ne se regénère pas.


Au passage, c'est possible les src de la version online? elle fonctionne super bien et est plus complète?
thx

**Comment by pictuga** [comment]
Issue 2yo, code base changed so much since then. Feel free to reopen the issue if it's still there ;)
