### ISSUE TITLE
TypeError when trying to generate feed from a specific page

### ISSUE THREAD

**Issue by clavelm** [pictuga/morss#104]
When I try to "feedify" that page https://chomsky.info/updates/ I'm getting a TypeError.
https://morss.it/:items=||*[class=thsxwwve]||li|a/https://chomsky.info/updates/
The XPath was generated by selecting the links on morss.it page.
![Screenshot_2022-09-28-09-59-31-14_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/717388/192723841-ccd0da2d-516a-410a-a743-a1123ac663d2.jpg)

**Comment by pictuga** [comment]
the TypeError you're talking about is just morss telling you that it couldn't generate a feed based on the info/xpath string it got. It works on my side with this link https://morss.it/:items=||li|a/https://chomsky.info/updates/ 

for reference: `raise TypeError('no way to handle this feed')`
