### ISSUE TITLE
Missing query variable names in URL

### ISSUE THREAD

**Issue by rishubil** [pictuga/morss#106]
I tried to create a feed like this:

https://morss.it/:items=||a[starts-with(@href,'|webtoon|detail')]:item_title=.||span[@class='name']/https://m.comic.naver.com/webtoon/list?titleId=670145

However, the URL of the generated feed is missing query variables name after `&`.

Example normal URL: `/webtoon/detail?titleId=670145&no=328&week=thu&listSortOrder=DESC&listPage=1`
Example generated URL: `/webtoon/detail?titleId=670145=328=thu=DESC=1`

**Comment by rishubil** [comment]
I took a look at the code to figure out what was causing the error.

When selecting the parser in the `parse` method of the `feeds.py` file, the problem occurs when using `FeedXML`. If I force it to use `FeedHTML`, it works fine.

There seems to be a conflict with the XML syntax when parsing `&` in the href attribute.

There are two ways to resolve this issue.

1) Add a `mode` option to allow the user to choose the parser.
2) In the `feedify.ini` file, add an entry for Naver webtoon mobile as shown below.

```ini
[naver webtoon mobile]
mode = html

path = https://m.comic.naver.com/webtoon/list?titleId=*

title = //head/meta[@property='og:title']/@content
desc = //head/meta[@property='og:description']/@content
items = //a[starts-with(@href,'/webtoon/detail')]

item_title = .//span[class=name]
item_link = ./@href
```

I think option 1 would be better, considering that a similar problem might arise on another website in the future.

**Comment by pictuga** [comment]
Thanks for the report and commit. Commit looks good. Will check it soon
