### ISSUE TITLE
Python Error downloading feed

### ISSUE THREAD

**Issue by itsamike** [pictuga/morss#119]
[One of my feeds](https://morss.it/https://app.newsloth.com/quicken-com/VlZQUlc.rss) is yielding a very fatal looking error. Anything we can do about that?

Thanks.

**Comment by pictuga** [comment]
Access seems heratic. Most likely blocked/throttled by newsloth.com. Nothing much we can do, except retry (link works right now)

**Comment by itsamike** [comment]
Thanks. I'll keep an eye on it.
