### ISSUE TITLE
Error loading feeds

### ISSUE THREAD

**Issue by Palatosino** [pictuga/morss#14]
I'm trying your online tool and it have problems with:

- [x] 1. http://www.sabercurioso.es/feed/ (Link provided is an HTML page, which doesn't link to a feed)
- [x] 2. https://www.libretro.com/index.php/feed/ (Error downloading feed)
- [x] 4. http://feeds.gawker.com/esgizmodo/full

Edit: Removed
3. https://blog.google/rss/ <-- I see that now they now are full text, so it doesn't need to pass by a full-text rss tool

**Comment by pictuga** [comment]
Hey, thanks for the report!

I'll fix the **1st** error soon, simple issue in the xml file detection function. Still have to investigate the others.

**Comment by pictuga** [comment]
All fixed in latest git version. Not yet pushed to test.morss.it and even less to morss.it.
