### ISSUE TITLE
Error Downloading Feed

### ISSUE THREAD

**Issue by meydman** [pictuga/morss#16]
Started having issues with feed (www.accountingtoday.com/feed?rss=true) through morss.it, results in Invalid SSL Certificate errors. Can you please help?

**Comment by juasiepo** [comment]
it works fine in my environment.

Can you provide some logs?

**Comment by pictuga** [comment]
Due to outdated version of morss and improper root certificate on morss.it
Overall upgrade of morss.it rolling out soon
