### ISSUE TITLE
readability

### ISSUE THREAD

**Issue by simevo** [pictuga/morss#17]
Hi, I am interested in this project. Previously I was looking at something similar (https://bitbucket.org/fivefilters/full-text-rss) but I was glad to discover morss since I prefer Python over PHP.

I noticed that some feeds are more difficult than others, for example on this one:
http://www.internazionale.it/sitemaps/rss.xml
morss does not really extract the content:
http://test.morss.it/www.internazionale.it/sitemaps/rss.xml

What works well is Firefox reading mode. After some research I found that it is based on the old readability.com javascript code, which is now here: https://github.com/mozilla/readability; it can be run standalone from node.js.

Chrome has a similar functionality in testing and the source for that is here: https://github.com/chromium/dom-distiller; this one seems more complex to tun as it depends on Java...

What is the best way to incorporate more sophisticated algorithms for content extraction in morss ?

And what about customizing the extraction rule on a site-by-site basis ? full-text-rss above has a repository of site-specific extraction rules: https://github.com/fivefilters/ftr-site-config

**Comment by pictuga** [comment]
Hi! Indeed the article detection algorithm is kinda problematic these days with morss... There are a couple of python ports of readability, and morss used to rely on them. However they were too slow (around 1 sec/article), which is not really a problem in a web browser, but quite problematic for morss (10 x 1 sec = 10 sec for one feed). Also, most of them either had poor encoding detection support or no python 2+3 support.

So I ended up developing my own readability fork (`morss/readabilite.py`), whose main target is _speed_ (by reducing the number of loops over the html tree, and keeping the code simple). I've been tweaking it for quite a while now, but it's still far from perfect (and new features always backfire until they are adjusted). All websites are born different, and some websites have really f*cked up page structure, on which even firefox readability fails to find the whole article (NYTimes and telegraph.co.uk are 2 good examples).

And to reply your question, the best way to incorporate other algorithms is to port them to python

I'll implement site-by-side rules when I'll be happy-enough with the algorithm ;) Manual rules should mostly be for edge cases (like xkcd and any website where the main content is not text).

I was also thinking about making it possible to pass an xpath rule to morss to tell which element to use as the article body, although I'm afraid many users won't know how to use it. Might have to work on some javascript bookmarklet to help them pick the elements they need.

All that will take some time to develop, feel free to participate :)

**Comment by simevo** [comment]
There is no silver bullet to solve this problem. The best would be to have all three options available, and choose on a site-by-site basis:
1) use the simplified readability implementation in Python (fast)
2) invoke nodejs readability from the python script (a bit slower but possibly more robust)
3) use an xpath rule (very precise but difficult to setup)

To 3), and in relation to a possible javascript bookmarklet, I should mention the **interative site config builder** provided by the PHP implementation I mentioned above: https://github.com/fivefilters/ftr-site-config-build 

To 1), I'd suggest relying on automated tests to improve the readability implementation in Python. Mozilla provide [a lot of tests](https://github.com/mozilla/readability/tree/master/test/test-pages) ready to use, we could pick up a subset of those.

To 2), I have timed the mozilla readability implementation wrapped by [this](https://github.com/joakimbeng/readability-from-string) as follows:
1) wget http://myurl
2) pipe the output of wget through this python script:
```
import sys
from bs4 import BeautifulSoup
content = sys.stdin.read()
soup = BeautifulSoup(content, 'lxml')
content_sanitized = soup.prettify()
print(content_sanitized)
```
3) create a nodejs script to process the sanitized html with readability-from-string using this template:
```
readabilityFromString = require('readability-from-string');
const html = `...`;
const readable = readabilityFromString(html, {href: 'http://myurl'});
console.log(readable);
```
The execution of `nodejs test.js ` takes < 0.3 s, that's not much to me considering that it must load nodejs ..

**Comment by pictuga** [comment]
Launching nodejs just for that is an overkill
The latest version (not pushed to github yet) works rather well with the feed mentioned
Closing for now
