### ISSUE TITLE
HTTPS feeds can't be processed

### ISSUE THREAD

**Issue by extrememicro** [pictuga/morss#24]
Only report that this is not working:
https://blog.sysaid.com/feed?post_type=sysaid_blog

https://morss.it/https://blog.sysaid.com/feed?post_type=sysaid_blog

**Comment by pictuga** [comment]
Thank you for the report!
The server is running on some outdated version of python, which doesn't support recent Https protocols. I've to switch to another server, but as this might lead to other bugs, I've been delaying the switch for quite a while. Will do it whenever I find time...

-----Original Message-----

**Comment by pictuga** [comment]
Seems like switching the current server from "legacy" to "stable" production environment was enough! (Hopefully other stuff hosted on the same server won't be affected...) Marking as solved for now :)
