### ISSUE TITLE
Running from CLI: relative import

### ISSUE THREAD

**Issue by Pseudavid** [pictuga/morss#25]
I'm a complete newbie and I'm really sorry if this is a very simple problem to solve, but I'd be grateful for any guidance. I'm trying to get a local RSS to CSV downloader. This is what happens when I run morss from the terminal (Ubuntu 18.10):

```
python -m morss debug http://feeds.bbci.co.uk/news/rss.xml

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/david/programas/morss/morss/morss.py", line 14, in <module>
    from . import feeds
ValueError: Attempted relative import in non-package
```

All solutions I find seem to suggest to change the script itself, not anything about the environment or the command. 

Thanks!

**Comment by pictuga** [comment]
try `cd ..` before running the python command.
You've to be at the root of the project code, not in the morss subfolder

**Comment by Pseudavid** [comment]
Thanks! I had already tried that, but using the path to the morss.py file. Sorry, I'm very new at this and it's obvious I don't even know how to correctly run python scripts, but now I've been able to do it. Thanks again.

**Comment by pictuga** [comment]
You're welcome!
