### ISSUE TITLE
broken compatibilty with python3

### ISSUE THREAD

**Issue by xaltsc** [pictuga/morss#26]
Hey, there is a bug when trying to run morss with python 3, namely, executing `python3 main.py "$FEED"` I get `ERROR: '%' must be followed by '%' or '(', found: '%a, %d %b %Y %H:%M:%S %Z\n%a, %d %b %Y %H:%M:%S %Z\n%Y-%m-%dT%H:%M:%SZ\n%Y-%m-%dT%H:%M:%SZ'`.

It seems to be related to the ConfigParser; this might be a related issue: https://github.com/CGATOxford/CGATPipelines/issues/335

**Comment by pictuga** [comment]
Fixed in f5acd2c14c68a !
