### ISSUE TITLE
detect whether the full content is already in rss feed

### ISSUE THREAD

**Issue by guyskk** [pictuga/morss#27]
> morss will also try to figure out whether the full content is already in place (for those websites which understood the whole point of RSS feeds). However this detection is very simple, and only works if the actual content is put in the "content" section in the feed and not in the "summary" section.

Many RSS feeds put full content in the "summary" or "description" section. I wander is there a better way to detect it.

Simply set content length threshold not work because there are many short feeds.
How about `is_fulltext = num_images > 0 or content_length > 2000`?

**Comment by pictuga** [comment]
True. "Auto detection" will be removed too. Fairly useless feature as people wouldn't use the tool if the feed is already full text...

**Comment by guyskk** [comment]
I don't understand why people wouldn't use the tool if the feed is already full text?

In real world many feeds are not well formated, but people do not care, they just want read all of them in the reader.

**Comment by pictuga** [comment]
I'm not sure I understand the use case. Feel free to elaborate or contribute some code. In the meantime, the code had been removed ages ago, so  closing for now
