### ISSUE TITLE
Facebook Connection fails

### ISSUE THREAD

**Issue by RandomRouter** [pictuga/morss#28]
When trying to connect with facebook following error appears:

> Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

**Comment by pictuga** [comment]
True. Facebook integration wasn't working very well and will be removed soon

**Comment by pictuga** [comment]
Code scrapped today (although not reflected in the online interface yet)
Feel free to contribute code if you want to reimplement it :)
