### ISSUE TITLE
Hacker news full text with comments 

### ISSUE THREAD

**Issue by Ramblurr** [pictuga/morss#29]
The Morss feed for hacker news is really great, however there's no easy way to access the comments.

I know Morss is more of a general rss tool, but any chance you'd consider adding features to combine the full text of hacker news posts and the comments?

**Comment by pictuga** [comment]
There is an option to keep the original feed content (including the "Comments" link for HN): in the feed preview, selet "More options: Output the [combined] feed...".

For HN, this would be https://morss.it/:clip/https:/news.ycombinator.com/rss

Does that reply your question?

**Comment by Ramblurr** [comment]
I was actually hoping for something where the full article text is followed by the comments, inline.  But that would require more processing.

This is probably close enough! Thanks.

**Comment by pictuga** [comment]
Ok, thanks for the feedback. Closing the issue for now :)
