### ISSUE TITLE
Simplest test give back an error

### ISSUE THREAD

**Issue by riccardoSocialcities** [pictuga/morss#3]
Hi!
I'd love to try your lib, but the simples example give me an error. I am trying to use morss as a library with the code

    import morss
    xml_string = morss.process('http://feeds.bbci.co.uk/news/rss.xml')

but i've got this error:

    Traceback (most recent call last):
      File "a.py", line 3, in <module>
        xml_string = morss.process('http://feeds.bbci.co.uk/news/rss.xml')
    AttributeError: 'module' object has no attribute 'process'

Can you help me?

**Comment by pictuga** [comment]
This commit should fix it fcf4197
I'm not fully sure about what __init__.py files should look like actually. Or you can try to `import morss.morss as morss` as a workaround

**Comment by pictuga** [comment]
Let me know if this commit didn't fix the issue for you :)

**Comment by riccardoSocialcities** [comment]
I solved with this import:
```
 from morss import morss
```
I think your commit should work too.
BTW great work, you should add it to PIP
