### ISSUE TITLE
feature request: forward website captcha (e.g. for fb pages)

### ISSUE THREAD

**Issue by gloschtla** [pictuga/morss#33]
I tried getting an rss feed of a public facebook page. (fb.com/pageUsername/posts) 

But fb requires me to prove that I'm human. 
It would be great if fb would accept the moRSS interface as non-robot.
a solution would be to let moRSS access the page through a dummy fb profile, as it is also done by archive.today

**Comment by pictuga** [comment]
won't fix. morss is an automated server, we can't expect you to solve captcha every hour when your rss reader refreshes the feed ;)
