### ISSUE TITLE
Not working on Android Police

### ISSUE THREAD

**Issue by skoshy** [pictuga/morss#40]
I'm trying to use Morss with Android Police, but I get an error saying it Couldn't load the feed.

https://www.androidpolice.com/feed

**Comment by pictuga** [comment]
It seems to work as of right now https://morss.it/https:/www.androidpolice.com/feed/ even tho none of the related code changed...

Anyway, closing for now, feel free to reopen the issue if need be!

**Comment by kpocius** [comment]
Looks like it's broken again.
