### ISSUE TITLE
Articles are not well detected/matched

### ISSUE THREAD

**Issue by imTHAI** [pictuga/morss#44]
Hello,

I have 2 websites that give rss link:
https://secouchermoinsbete.fr/feeds.atom
https://consomac.fr/rss/consomac.xml

But morss.it don't give the full text. Could you check ? 
Thank you

**Comment by Djeremaille** [comment]
Hello,

I don't know morss very well.
I tried different things with the first one but no good results.
For the second one, try with this:
https://morss.it/:clip/consomac.fr/actu.html

**Comment by imTHAI** [comment]
@dijeremaille
There is a difference. For example through morss.it, this news:
![Capture d’écran 2020-08-31 à 16 49 34](https://user-images.githubusercontent.com/36070606/91733656-22db8180-ebaa-11ea-9632-0a92a82c7dd6.png)



There is actually still text below the photo:
![Capture d’écran 2020-08-31 à 16 51 23](https://user-images.githubusercontent.com/36070606/91733721-3850ab80-ebaa-11ea-8bce-c205e95c1e82.png)

**Comment by Djeremaille** [comment]
Oui. Désolé. Je m'en suis rendu compte et j'ai retiré mon post...

**Comment by pictuga** [comment]
https://secouchermoinsbete.fr/feeds.atom

The articles are too short and therefore not caught by the auto detection algorithm

https://consomac.fr/rss/consomac.xml

Some of the articles are not well detected, with only part of the article being matched

There's no easy fix at the moment. The easiest option might be to make it possible to manually select the article.

**Comment by imTHAI** [comment]
Hello pictuga,

Thank you for check up.
I tried with another one free fullrss service I know: https://www.freefullrss.com/feed.php?url=https%3A%2F%2Fconsomac.fr%2Frss%2Fconsomac.xml&max=5&links=preserve&exc=&submit=Create+Full+Text+RSS
and it's full.
Don't take it wrong, it's not a criticism, it's just to say it can be fixed.

Thank you

**Comment by imTHAI** [comment]
Hello,

It's quite long time since this issue is open. It looks like this project is still in development (I thought not). 
Did you find any solution ?

KR,

**Comment by pictuga** [comment]
you can now use the `xpath` option to manually select the article in the pages
