### ISSUE TITLE
dependency missing

### ISSUE THREAD

**Issue by somedevreally** [pictuga/morss#48]
when i download and build the docker container, i see `package 'wheel' is not installed` how can i fix it? 

> 
> Building morss
> Step 1/5 : FROM alpine:latest
>  ---> a24bb4013296
> Step 2/5 : RUN apk add --no-cache python3 py3-lxml py3-gunicorn py3-pip git
>  ---> Using cache
>  ---> 5af6122bab90
> Step 3/5 : ADD . /app
>  ---> a670f3716eb1
> Step 4/5 : RUN pip3 install /app
>  ---> Running in 6b4f859dfe1a
> Processing /app
> Requirement already satisfied: lxml in /usr/lib/python3.8/site-packages (from morss==0.0.0) (4.5.1)
> Collecting bs4
>   Downloading bs4-0.0.1.tar.gz (1.1 kB)
> Collecting python-dateutil
>   Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
> Requirement already satisfied: chardet in /usr/lib/python3.8/site-packages (from morss==0.0.0) (3.0.4)
> Collecting pymysql
>   Downloading PyMySQL-0.10.1-py2.py3-none-any.whl (47 kB)
> Collecting beautifulsoup4
>   Downloading beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
> Requirement already satisfied: six>=1.5 in /usr/lib/python3.8/site-packages (from python-dateutil->morss==0.0.0) (1.15.0)
> Collecting soupsieve>1.2; python_version >= "3.0"
>   Downloading soupsieve-2.0.1-py3-none-any.whl (32 kB)
> Using legacy setup.py install for morss, since package 'wheel' is not installed.
> Using legacy setup.py install for bs4, since package 'wheel' is not installed.
> Installing collected packages: soupsieve, beautifulsoup4, bs4, python-dateutil, pymysql, morss
>     Running setup.py install for bs4: started
>     Running setup.py install for bs4: finished with status 'done'
>     Running setup.py install for morss: started
>     Running setup.py install for morss: finished with status 'done'
> Successfully installed beautifulsoup4-4.9.3 bs4-0.0.1 morss-0.0.0 pymysql-0.10.1 python-dateutil-2.8.1 soupsieve-2.0.1
> Removing intermediate container 6b4f859dfe1a
>  ---> fd192327b049
> Step 5/5 : CMD gunicorn --bind 0.0.0.0:8080 -w 4 --preload morss
>  ---> Running in e2194b9749eb
> Removing intermediate container e2194b9749eb
>  ---> 724ac9294c12
> 
> Successfully built 724ac9294c12

**Comment by pictuga** [comment]
well spotted, thanks!

fixed in 0629bb98fb0542179270778a193256bbf744c0da

**Comment by pictuga** [comment]
run `docker-compose build --no-cache --pull` to rebuild the image

**Comment by somedevreally** [comment]
great, that issue is fixed, now i see this error,


> [2020-10-03 19:25:10 +0000] [1] [INFO] Starting gunicorn 19.9.0
> [2020-10-03 19:25:10 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
> [2020-10-03 19:25:10 +0000] [1] [INFO] Using worker: sync
> 
> /usr/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used return io.open(fd, *args, **kwargs)
> 
> [2020-10-03 19:25:10 +0000] [8] [INFO] Booting worker with pid: 8
> 
> /usr/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used return io.open(fd, *args, **kwargs)
> 
> [2020-10-03 19:25:10 +0000] [9] [INFO] Booting worker with pid: 9
> 
> /usr/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used return io.open(fd, *args, **kwargs)
> 
> [2020-10-03 19:25:10 +0000] [10] [INFO] Booting worker with pid: 10
> 
> /usr/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used return io.open(fd, *args, **kwargs)
> 
> [2020-10-03 19:25:10 +0000] [11] [INFO] Booting worker with pid: 11

**Comment by pictuga** [comment]
thanks for the report

alpine package is apparently not up to date

fixed in 18ec10fe44515dbd60537bbb961981b5a4e068f4
