### ISSUE TITLE
morss only returns few articles from rss url

### ISSUE THREAD

**Issue by fiveteeghup** [pictuga/morss#49]
Hi,

I try to morss this url : http://www.lequipe.fr/Xml/actu_rss.xml
Morss.it only returns 9 articles although there are many more.

Is there a limitation on numbers of returned items?

**Comment by pargass31** [comment]
Hi, 
I have the same issue, do you finally solve it?

**Comment by pictuga** [comment]
This is actually by design. Loading more article would take too long for the server.

That being said, if your feed reader updates the feed every hour, you should be fine.

Otherwise, if you have specific uses, maybe try self-hosting morss?
