### ISSUE TITLE
[Feature Request] Link to embed YouTube videos from YouTube RSS

### ISSUE THREAD

**Issue by mdalpi** [pictuga/morss#5]
Hi there. I've been using this tool for some time, amazing work, thank you so much.
A few days back, after a lot of frustrations with the YouTube for iOS application I decided to remove all my subscriptions and turn that into RSS feeds.

But since YouTube feeds are crap, I tried using the moRSS but I get empty articles (but with the link to the original video). What I think it'll be great is that if we put a link to embed to the vídeo in the article, so for example in some iOS RSS readers it will use the native player.

The feeds from YouTube comes from the base URL:
http://gdata.youtube.com/feeds/base/users/[USERNAME]/uploads?client=ytapi-youtube-rss-redirect&alt=rss&orderby=updated&v=2

And the embed base URL is:
https://www.youtube.com/embed/[VIDEO_ID]

I will try to hack as soon as possible with your code, but I'm a beginner in Python, and only worked with Python 3 so there are some things that I will have to learn.
Thanks

**Comment by pictuga** [comment]
I've been working on a python 3 version of morss for the last few weeks. So you may want to wait for it to be finished before working on code. Python 3 will be easier for you to deal with and the port may break git auto merge.

I'll look into your feature request when I've time. I think it should be easy to hack it together.
