### ISSUE TITLE
[CRITICAL] WORKER TIMEOUT 

### ISSUE THREAD

**Issue by prtngrm** [pictuga/morss#51]
Hi,
I managed to get some results by fetching rss via morss.it. It takes a long time but it's working.
The url used: 
https://morss.it/:items=||*[class=dataList-cell]||a/https://platinmods.com/advancedsearch/advancedsearch-results?type=thread&keywords=&posted_by=&search_forums[]=156
The problem is that it doesn't work with my own server. After 30 seconds I get:
```
[2021-01-13 10:50:38 +0000] [30] [INFO] Booting worker with pid: 30
[2021-01-13 10:51:08 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:27)
[2021-01-13 10:51:08 +0000] [27] [INFO] Worker exiting (pid: 27)

```
Even if I put the TIMEOUT to more than 30 seconds the error come every 30 seconds.

What are the morss.it server parameters?

Here is my docker-compose.yml:
```
version: "2"
services:
  morss:
    build: /home/xxxxxx/sources/morss
    ports:
      - '9090:8080'
    restart: unless-stopped
    environment:
      - MAX_ITEM=100
      - LIM_TIME=-1
      - MAX_TIME=-1
      - LIM_ITEM=100
      - TIMEOUT=40
      - IGNORE_SSL=1
      - DEBUG=1

```
Another thing: Even with DEBUG=1 my docker logs don't return more infos.

**Comment by pictuga** [comment]
The timeout error comes from gunicorn (gunicorn kills the process if it takes too long to return sth). Try adding `--timeout 60` (default gunicorn value is 30sec)

Btw if you've a reverse proxy, note that the reverse proxy most likely also has a timeout in place. Nginx has a default of 60s

Your probably want to reduce LIM_ITEM a bit

As for DEBUG, I'll investigate. It maybe has sthbto do with gunicorn as well (and the lack of docker testing in my side....)

**Comment by pictuga** [comment]
As for morss.it server, it normally uses the default values (which can be seen in the source code)

**Comment by prtngrm** [comment]
Thanks for your reply.
I tried recompiling with the Dockerfile modified with the "-t" parameter and it's better.
I tuned the values of environment variables and have been able to have a result of 5 items once. I also had 9 items but they was showing only in the logs, the web page never display.
I will try to fine tune that but maybe I will make another container for this particular rss flux.

**Comment by pictuga** [comment]
DEBUG=1 should work with 95d6143636f4a9528915ec483ccf0ebcec9c51c8

As for your feed, maybe try setting `LIM_ITEM` to `-1` and `LIM_TIME` a few seconds more than your `MAX_TIME`

Also, I've added a segment on timeout in the readme 03cad120d00d9b9bb28df012930fc1f612580565

I guess your main concerns are now addressed, so closing the ticket for now. Let me know if otherwise

**Comment by martini1992** [comment]
For completeness, adding an environment variable like this:

```
environment:
  - GUNICORN_CMD_ARGS=-t 120
```

Will extend the gunicorn timeout
