### ISSUE TITLE
Couldn't load feed

### ISSUE THREAD

**Issue by dumprop** [pictuga/morss#53]
Couldn't load feed https://blog.path.net/.
Please try again later, or report on GitHub.

```
curl https://blog.path.net/
<html>
<head><title>307 Temporary Redirect</title></head>
<body>
<center><h1>307 Temporary Redirect</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

Looks like that site have anti bot protection

**Comment by pictuga** [comment]
> Looks like that site have anti bot protection

morss' server is blocked :/
