### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by buttabile** [pictuga/morss#55]
![immagine](https://user-images.githubusercontent.com/70759301/113478879-e3507d00-948b-11eb-9f69-963a0b56d6b3.png)
What's happening?

**Comment by pictuga** [comment]
Hi, hard to say like this. Which webpage/feed are you trying to run the service on?

**Comment by buttabile** [comment]
The feed is this.
https://sport.sky.it/rss/sport_nba.xml
Until 3 days ago it never gave any problems

**Comment by pictuga** [comment]
Hmm the error comes from the server of sky.it, either due to technical reasons or because they're blocking morss' server I'm afraid

**Comment by buttabile** [comment]
Thank you for your time!
