### ISSUE TITLE
Try to use class withouth success

### ISSUE THREAD

**Issue by prog-amateur2** [pictuga/morss#56]
Hello, thank you very much for your tool, it is a rare pearl in the web as it is today. 

I'm looking for a job, so I want to synchronize the different sources in my RSS reader, thus I do not have to always check every website. There are 3 french websites for which it is impossible for me to add them: 

1. Apec : https://www.apec.fr/candidat/recherche-emploi.html/emploi?motsCles=data%20scientist&lieux=711&sortsType=DATE
Here, according to Firefox tool's `Inspect Element`, the interesting class is `container-result` (the cardboard list)

2. Pôle Emploi : https://candidat.pole-emploi.fr/offres/recherche?lieux=11R&motsCles=data+scientist&offresPartenaires=false&range=0-19&rayon=10&tri=0
Here, the interesting class is `result-list list-unstyled`

3. Welcome to the jungle : https://www.welcometothejungle.com/fr/jobs?query=data%20scientist&page=1&aroundQuery=%C3%8Ele-de-France%2C%20France&refinementList%5Boffice.state%5D%5B0%5D=Ile-de-France&refinementList%5Boffice.country_code%5D%5B0%5D=FR
Here, the interesting class is `qjc24y-1 jhGOKF`

For each URL, I tried to customize the classes in morss.it but it doesn't work. What am I doing wrong? 

Thank you for your precious help!

**Comment by pictuga** [comment]
Hi, thanks for your message.
These 3 websites generate the content client-side (ie with javascript). morss however only parses plain html pages and can't see them. You are doing nothing wrong. Handling such websites would either (i) require to load javascript server-side by morss, which is a no-go in terms of resource, or (ii) make some hack-ish way to bypass it, which would take time to develop

**Comment by prog-amateur2** [comment]
Thank you very much, I appreciate your feedback. Too bad it can't be solved but I can understand that it is not as easy as I thought. I close this issue, but you can keep it open if you want. I wish you a nice week-end.
