### ISSUE TITLE
What is the refresh rate?

### ISSUE THREAD

**Issue by AlvesR0** [pictuga/morss#59]
Hello. What is the refresh rate? Gerei um rss atraves do morss. But it takes time to update.

Greetings,
AlvesRO.

**Comment by pictuga** [comment]
By default, feeds are cached 5 minutes minimum. Articles are cached 24h minimum.

**Comment by pictuga** [comment]
There was indeed a bug. The cache was never getting invalidated. Fixed in 917aa0fbc5
