### ISSUE TITLE
Re/Code not parsing?

### ISSUE THREAD

**Issue by fxer** [pictuga/morss#6]
Just getting empty story bodies when trying to parse Re/Code: http://morss.it/recode.net/feed/

sidenote: awesome app, just found it today and is working great on several site for me!

**Comment by pictuga** [comment]
Hmm… The app says it met some http errors while fetching the articles. Strange enough, but it seems to be working now at the address you gave. (If it happens again, you can try the test version at http://test.morss.it/recode.net/feed/ althu the results might be quite similar)
