### ISSUE TITLE
RSS feed by morss stopped working

### ISSUE THREAD

**Issue by nalegke** [pictuga/morss#60]
Hi, any ideas why the RSS feed just stopped working?
All three modes of 'full-text', 'original', 'combined (?)' return blank feed results for any website.

**Comment by pictuga** [comment]
Could you share some examples of feeds so I can test?

**Comment by nalegke** [comment]
https://morss.it/:proxy:items=%7C%7C*%5Bclass=title%5D%7C%7Ca/https://docs.microsoft.com/en-us/answers/index.html?sort=active&customPageSize=true&filters=all
https://morss.it/:items=%7C%7C*[class=title]%7C%7Ca/https://docs.microsoft.com/en-us/answers/index.html?sort=active&customPageSize=true&filters=all

https://morss.it/:proxy:items=%7C%7C*%5Bclass=home-tile-inside%5D%7C%7Cb/https://tradingeconomics.com
https://morss.it/:items=%7C%7C*[class=home-tile-inside]/https://tradingeconomics.com/

**Comment by pictuga** [comment]
should be solved (37f5a92b05764356baff305847a702c70afab2cd). can u check?

**Comment by nalegke** [comment]
Thanks a lot! All feeds are loading ok now.
Would it be possible to increase the max output from 10 to 20 items?

**Comment by pictuga** [comment]
Welcome! Max output is capped. The service is free and I don't want to overload the server ;) For more, I'd suggest you to host your own instance of the server.
