### ISSUE TITLE
Manipulate html before insertion into SQLite cache?

### ISSUE THREAD

**Issue by iNtEgraIR2021** [pictuga/morss#65]
Hi :wave:

it's me once again. Not sure if the following question popped up before. I checked the issues bug could find anything related:

I'd like to manipulate the html content of every feed item e.g. using beautifulsoup **before** morss inserts them into the SQLite cache.

Any idea how to do that? Help much appreciated 👍🏼 

Regards, Petra

**Comment by iNtEgraIR2021** [comment]
**Off topic:**

Searching the code I found the following in [`morss.py`](https://github.com/pictuga/morss/blob/ef6efd981c3232894c3b53c2ac73eac2ff95c9b0/morss/morss.py#L360):

```python
if options.ad:
        new = rss.items.append()
        new.title = "Are you hungry?"
        new.desc = "Eat some Galler chocolate :)"
        new.link = "http://www.galler.com/"
        new.time = "5 Oct 2013 22:42"
```
I'm a huge fan of chocolate 🍫 🥳 but ... are they a sponsor or is this part of a unit test or similar? I'm just curious I don't want to offend anyone.

**Comment by iNtEgraIR2021** [comment]
And there's a system path manipulation in [`feeds.py`](https://github.com/pictuga/morss/blob/62f2346b3f601c774655f33d8b7b1599ebc8b9e3/morss/feeds.py#L21)
```python
sys.path.append('/home/paul/Documents/Code/morss/lib')
```

Any chance to substitute that or add a condition e.g. some sort of debug or dev mode?

All the best, Petra 👋🏼

**Comment by pictuga** [comment]
> I'd like to manipulate the html content of every feed item e.g. using beautifulsoup before morss inserts them into the SQLite cache.

I'm not sure I see what type of use case you'd be willing to cover. Morss caches plain http requests, which are then re-processed every time the code is used. If you really want to go down that road, you might want to subclass `SQLiteCache` (but I'd rather advise against this). The `ad`/chocolate stuff below is probably where you want to add your own piece of code ;)

> I'm a huge fan of chocolate 🍫 🥳 but ... are they a sponsor or is this part of a unit test or similar? I'm just curious I don't want to offend anyone.

some debug test from some time ago (see de5b75162c4f378c9cba25ed105ed84bec7f32ab)

> And there's a system path manipulation in feeds.py

some awful plug that I never meant to push to git. I've been a bit heavy handed when running `git add -p`... I'll try to clean it out.

**Comment by pictuga** [comment]
> And there's a system path manipulation in feeds.py

removed

**Comment by iNtEgraIR2021** [comment]
> I'm not sure I see what type of use case you'd be willing to cover.

ok. Thank you for looking into this. Closing this for now. seems a lot more difficult than expected.
