### ISSUE TITLE
"Couln't load feed XXX Please try again later, or report on GitHub."

### ISSUE THREAD

**Issue by liar666** [pictuga/morss#68]
With XXX = https://www.linkedin.com/jobs/search?keywords=Data%20Science&location=St-%C3%89tienne%2C%20Auvergne-Rh%C3%B4ne-Alpes%2C%20France

I tried several times... So I'm reporting.

Seems LinkedIn is blocking something.

**Comment by pictuga** [comment]
LinkedIn blocked the server :/ Maybe try self hosting as an alternative. Nothing much I can offer I'm afraid.
