### ISSUE TITLE
"Couldn't load feed"

### ISSUE THREAD

**Issue by liar666** [pictuga/morss#71]
URL is in the error message:
```
Couldn't load feed https://www.kickassfacts.com/feed.
Please try again later, or report on GitHub.
```

I tried several times at various moments, I'm always getting the error message, whereas the feed is woking (but has truncated content, hence my need to use `morss`)

**Comment by pictuga** [comment]
morss' server can't successfully read from the kickassfacts server. Nothing much I can do about it I'm afraid :(
