### ISSUE TITLE
Oracle Blogs not working

### ISSUE THREAD

**Issue by sjkorvin** [pictuga/morss#74]
Hello. Thank you so much for morss.it. I've made extensive use of it expanding RSS feeds for use in Inoreader.

I cannot get Oracle Blogs to work on your site. When I try to create a custom feed in Inoreader's premium plan, I get a line of text saying that Javascript is required to view the page.

The URL for the feed that I am trying to expand is ```https://blogs.oracle.com/cloud-infrastructure/rss```. I would appreciate any assistance in helping to resolve this matter. Thank you again.

**Comment by pictuga** [comment]
morss server can't connect to the server. i definitely expect big corporate oracle not to be too bot friendly
