### ISSUE TITLE
[Doc] wrong variable name in README ?

### ISSUE THREAD

**Issue by typhoe** [pictuga/morss#76]
Hi,

the readme says:
CACHE=diskcache: disk-based cache. Target directory canbe defined with DISKCAHE_DIR

Shouldn't the variable be DISKCACHE_DIR ?

Thank you for this program!

**Comment by pictuga** [comment]
Turns out the readme is correct as the code is also wrong... Well spotted thanks, will fix it

**Comment by typhoe** [comment]
No problem, and thank you!

**Comment by pictuga** [comment]
Should be fixed in d17b9a2f2733f5ddcf8fa61f3877fc3fcb3ef8fa
