### ISSUE TITLE
/bin/sh: can't open '/app/docker-entry.sh': No such file or directory

### ISSUE THREAD

**Issue by oliroe** [pictuga/morss#77]
Latest version showing the same issue again as reported recently

#70 

![image](https://user-images.githubusercontent.com/4500141/147419091-5cd651b9-46a5-44f8-b7c7-1782aa72ba0e.png)

**Comment by pictuga** [comment]
Hi, which OS are you using? Are you building from git or using docker image? It's a bit strange that it tries to use `docker-entry.sh` as it has been renamed (including on docker hub https://hub.docker.com/layers/pictuga/morss/latest/images/sha256-b259a4386327447a7395fcef032afc28b235869ac9e6fdbee97bc0f843753cb3?context=explore )

**Comment by oliroe** [comment]
Apologies, think I may have wasted your time. There must have been an issue with me pulling the latest image. I've scrapped my installation and started again and all is good

Sorry again

**Comment by pictuga** [comment]
No worries. It's always good to report issues ;)
