### ISSUE TITLE
error: cannot uninstall 'packaging'

### ISSUE THREAD

**Issue by aberlaas** [pictuga/morss#78]
Hi,

For some reasons I can't run docker. Build fails with the following error : 

> ERROR: Cannot uninstall 'packaging'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Thank you,

**Comment by aberlaas** [comment]
I can see 'packaging 20.9' is installed first when the following command is called :

> apk add --no-cache --virtual .run-deps python3 py3-lxml py3-setproctitle py3-setuptools;

An then, it tries to reinstall it (version 21.3) when the following command is called : 

> apk add --no-cache --virtual .build-deps py3-pip py3-wheel;

I'm using armbian distib.

**Comment by pictuga** [comment]
Issue comes from pip trying to uninstall sth installed with apk. Solved in 2a7a1b83ecb8125927003132c1a333e9f48e5c97 by using a more up-to-date version of the alpine image. Thanks for reporting!
