### ISSUE TITLE
Python errors

### ISSUE THREAD

**Issue by Noexpert** [pictuga/morss#83]
I'm seeing Python errors here:
https://morss.it/:items=||*[class*=%22Text__text___3eVx1j%20Text__dark-grey___AS2I_p%20Text__medium___1ocDap%22]/https://www.reuters.com/world/uk/

Unclear whether this is server related, or bad syntax on my part.

**Comment by gayatrisingh31** [comment]
Hi @pictuga can i do it ?

**Comment by pictuga** [comment]
Problem is twofold

1. The xpath rule and doesn't match anything. You probably want sth like `:items=||*[contains(@class,'xyz_')]`

2. There was an outstanding issue with the feed converter (from html to rss). Now solved with 32d9bc9d9dfea03792636ef62d70911d0ec25837.

You feed should now work at https://morss.it/:items=%7C%7C*[contains(@class,'StoryCollection__story')]/https://www.reuters.com/world/uk/

**Comment by pictuga** [comment]
@gayatrisingh31 thanks for the offer! Im afraid I already settled the issue. Feel free to poke around the code if you see anything worth servicing ;) Getting a more helpful `index.html` is probably a nice place to start otherwise.

**Comment by pictuga** [comment]
Closing for now. Feel free to reopen if needed!

**Comment by Noexpert** [comment]
Thanks!
