### ISSUE TITLE
Le flux rss est bloqué par l editeur

### ISSUE THREAD

**Issue by Thbtst** [pictuga/morss#86]
Bonjour 

https://radiofrance-podcast.net/podcast09/rss_21168.xml

Le flux rss proposé par cette emission renvoie une information pour installer l application Radio France

Ce n est pas le cas pour le flux suivant:
https://radiofrance-podcast.net/podcast09/rss_10901.xml

Dans les deux cas j ai clique sur le bouton flux rss propose sur la page de l émission

J utilise Google Podcast 

Merci

**Comment by pictuga** [comment]
Bonjour, c'est normal, le flux https://radiofrance-podcast.net/podcast09/rss_21168.xml ne contient qu'un lien vers le site de l'appli (et aucun épisode de podcast) ;) https://radiofrance-podcast.net/podcast09/rss_10901.xml contient quant à lui des épisodes normaux

**Comment by pictuga** [comment]
Closing as the issue is not due to morss but to the upstream rss feed
