### ISSUE TITLE
[Help Request] Dealing with a RSS link from Ranidrop.oi

### ISSUE THREAD

**Issue by FelipeRearden** [pictuga/morss#87]
Hello @pictuga !!!!!!

First of all, thank you very much for creating this amazing. I'm facing some problems with truncated RSS feeds and I came after a recommendation from a friend

Let me explain my Issue to see if you can help me :pray: !!!!

There an app called [Raindrop.io](https://raindrop.io) that lets the user save links (its a bookmark manager) and organize them by folders. BUT it has a killer feature:
- You can create a RSS link from each folder and open this RSS in any RSS Reader (NetNewsWire) for example.

The problem is that it generates a truncated RSS feeds :)

### Here is my problem 

When using the raindrop link with wit `morss` I was not able to retrieve ALL CONTENT from my raindrop feed. 

For example: one of my feeds have 50 link (which seems to be the limit of raindrop for RSS feed)
- When opening this link with NetNewWire iI get 50 links
- When using `morss` link I only get 5/10 links 

I tried to change the parameters `output` `feed as` `using the` `link of the` `items and` but only get a subset of the total :(

I repeat the test with a 20link feed and I only get 4 links.

---

I hope you could give some help with this issue :pray: 
Would be amazing for me to be able to finally import my raindrop feed to my knowledge system :)

---

Thanks for reading this :)

Let me know if you need more information. 

I wish you a fantastic day

**Comment by pictuga** [comment]
Hey! The cap at 5 articles is intentional ;) It would otherwise take use too much resources from the server (especially for a free service!). Note that once articles are cached, morss can process 5 more articles. This limit of 5 is enough for most use cases, as your feed reader will refresh the feed periodically.

**Comment by pictuga** [comment]
Alternative would be for you to self-host the tool ;) Closing for now as this is not a "bug" per se

**Comment by FelipeRearden** [comment]
Hello @pictuga !!!!

Thank you very much for your feedback. It's 100% crystal clear to me right know 

Thank you for this amazing tool !

Have a great day!
