### ISSUE TITLE
vars in url are ignored

### ISSUE THREAD

**Issue by HasClass0** [pictuga/morss#88]
Hello,
Since about 2 days, it looks like vars in urls like "...&category=4..." are ignored when setting the Xpath rule.
So the returned feed for a category has all the site publications. 
Or the crawled site return an error, so the Xpath rule setting interface does not show the target.

examples:
https://morss.it/:items=||*[class=tgxtablecell]||a|b/https:/torrentgalaxy.to/torrents.php?c41=1&c11=1&c6=1&lang=0&nox=1&search=
==>> OK for setting the Xpath rule, but on the index page, the results are not filtered. 

https://torrentgalaxy.to/torrents-hotpicks.php?cat=3
==>> Category/ID ignored: error message -> can't set the Xpath rule.

I take this opportunity to thank you for this very usefull tool.

**Comment by pictuga** [comment]
Hey! Thanks for reporting. Probably a regression from d6b90448f3db. Will loo at it in the coming days. The work-in-progress auto testing (pytest) should avoid such regressions moving forward.

**Comment by HasClass0** [comment]
Ok. 
Thanks again for your work. :1st_place_medal:

**Comment by HasClass0** [comment]
Back to normal for me. :ok_hand: 
Thanks for the update.

**Comment by pictuga** [comment]
Welcome! Fixed in 4d64afe9cb. I've added tests related to URL handling to avoid future regressions on this.
