### ISSUE TITLE
Failed to load BleepingComputer

### ISSUE THREAD

**Issue by Zeit08** [pictuga/morss#98]
Hi, the error message on morss.it is to try again later (I did) or to report to GitHub (doing right now). Basically the link [https://www.bleepingcomputer.com/feed/](https://www.bleepingcomputer.com/feed/) does not get processed by morss.
_Tried on latest Brave stable and Firefox stable. OS: Fedora 36_

**Comment by eneusta1** [comment]
Same problem here ; using Version 102.0.5005.115 (Official Build) (arm64)

**Comment by Ovler-Young** [comment]
My self-host one can handle it. Maybe the public server ip is banned.

**Comment by pictuga** [comment]
> My self-host one can handle it. Maybe the public server ip is banned.

looks like it
